format_version: 1

pipelines:
  dhruv:
    group: test-gocd
    label_template: ${COUNT}
    materials:
      repo:
        git: git@github.com:dhruvguptaTTN/test-gocd.git
        branch: main
    stages:
      - BuildStage:
          jobs:
            - BuildJob:
                tasks:
                  - exec:
                      command: chmod
                      arguments:
                        - +x
                        - test.sh
                  - exec:
                      command: ./test.sh
