format_version: 1
pipelines:
  dhruv:
    group: test-gocd
    label_template: ${COUNT}
    template: test-gocd
    materials:
      repo:
        git: git@github.com:dhruvguptaTTN/test-gocd.git
        branch: main
